### PR TITLE
AttributeError 'server' when StorageServer creation fails

### PR DESCRIPTION
**Pull request by stefanholek**
When `StorageServer.__init__` fails with an exception, the error is masked by a subsequent AttributeError: 'ZEOServer' object has no attribute 'server'.

I propose to add a close_server function to ZEOServer, which can handle the case of non-existing server. This is also for the benefit of subclasses, which get better access to the server lifecycle.

### CODE REVIEW

**Comment by mgedmin** [comment]
LGTM.

I've restarted the failed Travis build on Python 3.3, to see if that failure is reproducible.
